# Generated by Django 3.2.7 on 2021-10-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='texthalf',
            field=models.CharField(default='Some text...', max_length=450),
        ),
    ]
