# Generated by Django 3.2.7 on 2021-10-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_texthalf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='texthalf',
            field=models.CharField(default=models.TextField(), max_length=450),
        ),
    ]
