# Generated by Django 3.2.7 on 2021-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_texthalf'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='textinfo',
            field=models.CharField(default=' ', max_length=450),
        ),
    ]
