# Generated by Django 3.2.7 on 2021-10-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_textinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='textinfo',
            field=models.CharField(default='О чем ваш текст?', max_length=450),
        ),
    ]
