# Generated by Django 3.2.7 on 2021-10-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211030_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Incredible')]),
        ),
    ]
