# Generated by Django 3.2.7 on 2021-11-02 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Post Likes', 'verbose_name_plural': 'Лайка'},
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like',
            field=models.IntegerField(default=True, verbose_name='Число лайков'),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='liked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_post_main', to=settings.AUTH_USER_MODEL),
        ),
    ]
