# Generated by Django 3.2.7 on 2021-11-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20211102_0703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'verbose_name': 'Post Likes', 'verbose_name_plural': 'Лайки'},
        ),
        migrations.AlterField(
            model_name='postlike',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Лайк'),
        ),
    ]
