# Generated by Django 3.2.7 on 2021-11-02 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0017_auto_20211102_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_or_dislike', models.CharField(choices=[('LIKE', 'like'), ('DISLIKE', 'dislike'), (None, 'None')], default=None, max_length=7)),
            ],
            options={
                'verbose_name': 'Post Likes',
                'verbose_name_plural': 'Лайки',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='post_dislike',
            field=models.IntegerField(default=0, verbose_name='Дизлайк'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_like',
            field=models.IntegerField(default=0, verbose_name='Лайк'),
        ),
        migrations.DeleteModel(
            name='PostLike',
        ),
        migrations.AddField(
            model_name='like',
            name='for_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
