# Generated by Django 3.2.7 on 2021-11-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20211102_0730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Post Likes', 'verbose_name_plural': 'Лайка'},
        ),
    ]
