# Generated by Django 3.2.9 on 2021-12-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20211208_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='WoT', max_length=255),
        ),
    ]
