# Generated by Django 3.2.9 on 2021-11-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.PositiveSmallIntegerField(choices=[(1, 'WOT'), (2, 'Pubg')], default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='textinfo',
            field=models.CharField(default='О чем ваш текст?', max_length=250),
        ),
    ]
