# Generated by Django 3.2.9 on 2021-11-21 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20211116_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='game',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='N/G', max_length=255),
        ),
    ]
