# Generated by Django 3.2.9 on 2021-11-25 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_rename_user_user_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
