# Generated by Django 3.2.9 on 2021-12-07 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_user_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
